name: Build Debian installers
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - debian/installers/**
jobs:
  push:
    name: "images:${{ matrix.installers }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        installers:
          - base
          - java
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./debian/installers/${{ matrix.installers }}
          file: ./debian/installers/${{ matrix.installers }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/panszelescik/images:debian-installer_${{ matrix.installers }}
