name: Build Java
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - debian/java/**
jobs:
  push:
    name: "images:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 8j9
          - 11
          - 11j9
          - 13
          - 13j9
          - 14
          - 14j9
          - 15
          - 15j9
          - 16
          - 16j9
          - 17
          - 17j9
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./debian/java/${{ matrix.tag }}
          file: ./debian/java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/panszelescik/images:debian-java_${{ matrix.tag }}
