name: Build Installers
on:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - main
    paths:
      - installers/**
jobs:
  push:
    name: "installers:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - debian
          - debian_java
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./installers/${{ matrix.tag }}
          file: ./installers/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/panszelescik/installers:${{ matrix.tag }}
