name: Build Java Test
on:
  push:
    branches:
      - main
    paths:
      - java_test/**
jobs:
  push:
    name: "java_test:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 16
          - 17
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./java_test
          file: ./java_test/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/panszelescik/java_test:${{ matrix.tag }}
