name: Build Java Nginx
on:
  schedule:
    - cron: "0 4 * * 2"
  push:
    branches:
      - main
    paths:
      - java_nginx/**
jobs:
  push:
    name: "java_nginx:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./java_nginx
          file: ./java_nginx/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/panszelescik/java_nginx:${{ matrix.tag }}
